import { Sizes } from '@/constants/sizes'
import { StyleSheet } from 'react-native'

export const characterDetailsStyles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: '#FFFFFF',
	},
	fullScreenContainer: {
		flex: 1,
		backgroundColor: '#1F2937',
	},
	backButton: {
		backgroundColor: '#3B82F6',
		paddingHorizontal: 24,
		paddingVertical: 12,
		borderRadius: 8,
	},
	backButtonText: {
		color: '#FFFFFF',
		fontSize: 16,
		fontWeight: '600',
	},
	heroSection: {
		height: Sizes.SCREEN_HEIGHT * 0.6,
		position: 'relative',
		backgroundColor: '#F1F5F9',
	},
	heroGradient: {
		position: 'absolute',
		top: 0,
		left: 0,
		right: 0,
		height: 250,
		zIndex: 2,
	},
	backButtonContainer: {
		position: 'absolute',
		top: 50,
		left: 24,
		zIndex: 3,
	},
	headerBackButton: {
		width: 48,
		height: 48,
		borderRadius: 24,
		backgroundColor: 'rgba(255, 255, 255, 0.95)',
		justifyContent: 'center',
		alignItems: 'center',
		shadowColor: '#000',
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.3,
		shadowRadius: 8,
		elevation: 8,
		borderWidth: 1,
		borderColor: 'rgba(255, 255, 255, 0.2)',
	},
	backIcon: {
		fontSize: 22,
		color: '#1F2937',
		fontWeight: 'bold',
		marginLeft: -2, // Optical alignment
	},
	favoriteButtonContainer: {
		position: 'absolute',
		top: 50,
		right: 24,
		zIndex: 3,
	},
	imageContainer: {
		flex: 1,
		justifyContent: 'center',
		alignItems: 'center',
	},
	characterImage: {
		width: Sizes.SCREEN_WIDTH * 0.65,
		height: Sizes.SCREEN_WIDTH * 0.65,
		borderRadius: Sizes.SCREEN_WIDTH * 0.325,
		borderWidth: 8,
		borderColor: '#FFFFFF',
		shadowColor: '#000',
		shadowOffset: { width: 0, height: 12 },
		shadowOpacity: 0.4,
		shadowRadius: 20,
		elevation: 16,
	},
	contentContainer: {
		backgroundColor: '#FFFFFF',
		borderTopLeftRadius: 32,
		borderTopRightRadius: 32,
		marginTop: -32,
		paddingTop: 32,
		paddingHorizontal: 24,
		paddingBottom: 40,
		zIndex: 1,
	},
	nameSection: {
		alignItems: 'center',
		marginBottom: 32,
	},
	characterName: {
		fontSize: 32,
		fontWeight: 'bold',
		color: '#1F2937',
		textAlign: 'center',
		marginBottom: 16,
	},
	statusBadge: {
		flexDirection: 'row',
		alignItems: 'center',
		paddingHorizontal: 16,
		paddingVertical: 8,
		borderRadius: 20,
	},
	statusText: {
		fontSize: 16,
		fontWeight: '600',
	},
	infoGrid: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		marginBottom: 32,
		gap: 16,
	},
	infoCard: {
		flex: 1,
		backgroundColor: '#F8FAFC',
		padding: 20,
		borderRadius: 16,
		borderWidth: 1,
		borderColor: '#E2E8F0',
	},
	infoLabel: {
		fontSize: 14,
		color: '#64748B',
		fontWeight: '500',
		marginBottom: 4,
	},
	infoValue: {
		fontSize: 18,
		color: '#1E293B',
		fontWeight: '600',
	},
	sectionTitle: {
		fontSize: 20,
		fontWeight: 'bold',
		color: '#1F2937',
		marginBottom: 16,
	},
	locationContainer: {
		gap: 16,
		marginBottom: 32,
	},
	locationCard: {
		backgroundColor: '#F8FAFC',
		padding: 20,
		borderRadius: 16,
		borderWidth: 1,
		borderColor: '#E2E8F0',
	},
	locationLabel: {
		fontSize: 14,
		color: '#64748B',
		fontWeight: '500',
		marginBottom: 8,
	},
	locationName: {
		fontSize: 18,
		color: '#1E293B',
		fontWeight: '600',
		marginBottom: 4,
	},
	locationType: {
		fontSize: 14,
		color: '#3B82F6',
		fontWeight: '500',
		marginBottom: 2,
	},
	locationDimension: {
		fontSize: 14,
		color: '#6B7280',
		fontStyle: 'italic',
	},
	episodesScroll: {
		marginBottom: 32,
	},
	episodeCard: {
		backgroundColor: '#F8FAFC',
		padding: 16,
		borderRadius: 12,
		borderWidth: 1,
		borderColor: '#E2E8F0',
		width: 160,
		marginRight: 12,
	},
	episodeNumber: {
		fontSize: 14,
		fontWeight: 'bold',
		color: '#3B82F6',
		marginBottom: 4,
	},
	episodeName: {
		fontSize: 14,
		fontWeight: '600',
		color: '#1E293B',
		marginBottom: 8,
		lineHeight: 18,
	},
	episodeDate: {
		fontSize: 12,
		color: '#6B7280',
	},
	moreEpisodesCard: {
		backgroundColor: '#EFF6FF',
		padding: 16,
		borderRadius: 12,
		borderWidth: 1,
		borderColor: '#DBEAFE',
		width: 120,
		justifyContent: 'center',
		alignItems: 'center',
	},
	moreEpisodesText: {
		fontSize: 14,
		fontWeight: '600',
		color: '#3B82F6',
	},
	additionalInfo: {
		marginBottom: 32,
	},
	createdInfo: {
		alignItems: 'center',
		paddingTop: 24,
		borderTopWidth: 1,
		borderTopColor: '#E2E8F0',
	},
	createdLabel: {
		fontSize: 14,
		color: '#64748B',
		fontWeight: '500',
		marginBottom: 4,
	},
	createdDate: {
		fontSize: 16,
		color: '#1E293B',
		fontWeight: '600',
	},
})
